<footer class="footer-whole">

    <!--the left section of the footer-->
    <div class="footer-leftside">
      <img src="images/Swinburne-post-white.png" alt="company-logo">
    </div>

    <!--the right section of the footer-->
    <div class="footer-rightside"> 
      <div class="column-1">
        <p><strong>INFO</strong></p>
        <ul>
          <li><a href=#>Enhancements</a></li>
          <li><a href=#>References</a></li>
          <li><a href=#>Terms and Services</a></li>
          <li><a href=#>Q&A</a></li>
          <li><a href=#>About us</a></li>
        </ul>
      </div>

      <div class="column-second">
        <p class="follow"><strong>FOLLOW US</strong></p>
        <div class="column-second-logo">
          <img id="facebook" src="images/556-5568208_facebook-icon-facebook-icon-dark-grey.png" alt="facebook">
          <img id="discord" src="images/discord.81cfd5c2.png" alt="discord">
          <img id="youtube" src="images/dea6jor-4e0e1daf-3b5a-4ffc-b876-a04aed600319.png" alt="youtube">
        </div>
      </div>
      <div class="last-line">
          <p class="company-line"> &#169; Company's name 2023 Powered by Mercury</p>
      </div>
    </div>


      <p class="footer-middle">	&#8212;	&#8212; &#8212;	&#8212;	&#8212;	&#8212; &#8212; &nbsp; &#64; Swinburne University of Technology &nbsp; &#8212; &#8212;	&#8212;	&#8212;	&#8212;	&#8212;	&#8212;</p>

    
</footer>