<header class="header-main">
      <div class="header-main-logo">  
        <a href="index.php"><img src="images/linus.png" alt="Group logo"></a>
        <nav class="header-main-nav">
          <ul>
            <li><a href="index.php">HOME</a></li>
            <li><a href="jobs.php">JOBS</a></li>
            <li><a href="apply.php">JOB APPLICATIONS</a></li>
            <li><a href="about.php">ABOUT US</a></li>
            <li><a href="enhancement.php">ENHANCEMENTS</a></li>

          </ul>
          
        </nav>
      </div>

      <div class="header-main-sm">
        <!--Youtube Logo linking to the Video-->
        <a href="https://youtu.be/8s4n-oNvX2I" target="_blank"><div class="header-main-sm-yt"></div></a>
      </div>
    </header>